#pragma once
#define OPTION_CREATE_TEXT "1 - utworz obiekty CTable"
#define OPTION_LENGTH_TEXT "2 - okresl dlugosc tablicy dla obiektu"
#define OPTION_DELETE_TEXT "3 - skasuj obiekt"
#define OPTION_DELETE_ALL_TEXT "4 - skasuj wszystkie obiekty"
#define OPTION_SET_NAME_TEXT "5 - nadaj nazwe obiektowi"
#define OPTION_CLONE_TEXT "6 - sklonuj obiekt i dodaj do puli"
#define OPTION_PRINT_TEXT "7 - wypisz obiekt"
#define OPTION_SET_CELL_TEXT "8 - wpisz wartosc do komorki obiektu"
#define OPTION_EXIT_TEXT "9 - zakoncz"

#define CREATE_CONSTRUCTOR_TYPE "Wybierz typ konstruktora dla nowych obiektow: "
#define CREATE_DEFAULT "1 - konstruktor domyslny"
#define CREATE_PARAMETRIC "2 - konstruktor parametryczny"
#define CREATE_COUNT "ile obiektow: "

#define OBJECT_INDEX "indeks obiektu: "
#define CELL_INDEX "indeks komorki: "
#define GET_NAME "nazwa tablicy: "
#define GET_VALUE "wartosc komorki: "
#define TABLE_LENGTH "dlugosc tablicy: "
#define VECTOR_INDEX_OUT_OF_BOUNDS "indeks poza granicami wektora, aktualny rozmiar to: "
#define VECTOR_EMPTY "wektor jest aktualnie pusty, by wykonac te operacje najpierw dodaj obiekty"

#define POSITIVE "wartosc musi byc dodatnia!"
#define NONNEGATIVE "wartosc musi byc nieujemna!"
#define NOT_A_NUMBER "wartosc musi byc liczba!"

#define WELCOME_MSG "Witaj w programie! Co chcesz zrobic?: "
#define WRONG_COMMAND "Bledna komenda, podaj ponownie: "
#define INSERT_COMMAND "Podaj komende: "

#define DEFAULT_COMMAND "Komenda domyslna"

#define NAME "nazwa: "
#define COMMAND_SPACED "  komenda: "
#define COMMAND "komenda: "
#define COMMAND_TO_REMOVE "komenda elementu do usuniecia: "
#define COMMAND_NOT_FOUND "Nie ma takiej komendy"
#define WRONG_TYPE "Bledny typ"
#define BACK "back"
#define ADD_ITEM "dodaj elem"
#define REMOVE_ITEM "usun elem"
#define ITEM_TYPE "Jaki element chcesz dodac (CMenuCommand/CMenu): "
#define TYPE_CMENUCOMMAND "CMenuCommand"
#define TYPE_CMENU "CCommand"
#define NAME_TAKEN "istnieje juz element o takiej nazwie"
#define COMMAND_TAKEN "istnieje juz komenda o takiej nazwie"
#define SUCCESS_TEXT "dzialanie zakonczone powodzeniem"